### ISSUE TITLE
Error Processing HYDE Data in Landuse Module

### ISSUE THREAD

**Issue by KaixuanDai** [PIK-LPJmL/LandInG#1]
Hi, I am trying to process the HYDE data in the landuse module. When running the script [step2_hyde_convert.sh](https://github.com/PIK-LPJmL/LandInG/blob/main/landuse/HYDE/step2_hyde_convert.sh), I encountered the following error:

```bash

cdo setreftime: Open failed on >ncdf_tmp/1500AD_lu/conv_rangeland_1500.nc4<
Unsupported file type (library support not compiled in)

```
To resolve this issue, I recompiled and reinstalled the CDO program using the following configuration:
```
./configure --enable-netcdf4 --enable-szlib --enable-hdf5 --with-netcdf=/usr/lib/x86_64-linux-gnu --with-hdf5=/usr/lib/x86_64-linux-gnu/hdf5/serial/ --with-szlib=/usr/lib/x86_64-linux-gnu
```
However, after reinstallation, the options nc4 and -z zip are reported as invalid. I suspect this is due to compatibility issues between the cdo-1.9 version and the libnetcdf version.

Could you please provide some information about the compatibility between different versions of CDO and libnetcdf?

**Comment by sostberg** [comment]
We cannot provide system-specific information on compatibility between CDO and libnetcdf since this depends on the versions installed in your system. The format "nc4c" should be supported by current versions of CDO. zip compression may require external libraries linked to the NetCDf library. If you're experiencing problems here you could try to remove the -z zip flag, which will lead to uncompressed intermediate results (larger files).

**Comment by sostberg** [comment]
Closing since this is not directly related to LandInG.
